### ISSUE TITLE
Will this plugin be available in intellij idea?

### ISSUE THREAD

**Issue by aristotll** [JetBrains/ruby-type-inference#36]
Current it is only supported in Rubymine, and we cannot use it in intellij idea even if we install the Ruby Plugin.

**Comment by valich** [comment]
@nikitabobko I suppose we should replace `com.intellij.modules.ruby` dependency by something more flexible

**Comment by nikitabobko** [comment]
Plugin is compatible with IntelliJ IDEA 2019.1 — 2019.1.3 (rc). I've managed to install it in IntelliJ IDEA 2019.1. I guess that you've used some previous version. @aristotll check it with 2019.1 and give us feedback. 

Thank you!

**Comment by aristotll** [comment]
@nikitabobko  It seems there are some problems maybe.

```
Traceback (most recent call last):
	3: from ~/.rvm/rubies/ruby-2.6.2/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	2: from ~/.rvm/rubies/ruby-2.6.2/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	1: from ~/.rvm/gems/ruby-2.6.2/gems/arg_scanner-0.3.0/lib/arg_scanner/starter.rb:10:in `<top (required)>'
~/.rvm/gems/ruby-2.6.2/gems/arg_scanner-0.3.0/lib/arg_scanner/starter.rb:10:in `require_relative': cannot load such file -- ~/.rvm/gems/ruby-2.6.2/gems/arg_scanner-0.3.0/lib/arg_scanner/arg_scanner (LoadError)
```

**Comment by dmolesUC** [comment]
@nikitabobko How did you install it? I'm not seeing it as available in Ultimate 2019.2.4.

**Comment by donv** [comment]
I have been using this plugin with IntelliJ idea 2019.x for a long time now.  I installed it in the plugin manager same as any plugin.

It is marked as incompatible with IntelliJ idea 2020.x.  Any chance of making it compatible?

**Comment by hurricup** [comment]
@donv we've not decided yet what to do with it.
