### ISSUE TITLE
JRuby Support

### ISSUE THREAD

**Issue by aryeh-looker** [JetBrains/ruby-type-inference#37]
Curious if JRuby might be supported. Getting the following at the moment when attempting to install the gem by placing it in my Gemfile and running `bundle install`.

```
current directory: /Users/user/.rvm/gems/jruby-9.1.17.0@aryeh/gems/arg_scanner-0.3.0/ext/arg_scanner
/Users/user/.rvm/rubies/jruby-9.1.17.0/bin/jruby -r ./siteconf20190521-5756-1609kxo.rb extconf.rb
LoadError: no such file to load -- debase/ruby_core_source
  require at org/jruby/RubyKernel.java:956
  require at /Users/user/.rvm/rubies/jruby-9.1.17.0/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:55
   <main> at extconf.rb:5
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/Users/user/.rvm/rubies/jruby-9.1.17.0/bin/jruby

extconf failed, exit code 1
```

**Comment by Portersson** [comment]
Getting a similar error here too

`Building native extensions. This could take a while...
ERROR:  Error installing arg_scanner:
        ERROR: Failed to build gem native extension.

    current directory: C:/Ruby24/lib/ruby/gems/2.4.0/gems/arg_scanner-0.3.0/ext/arg_scanner
C:/Ruby24/bin/ruby.exe -r ./siteconf20190523-24376-1ectvp2.rb extconf.rb
checking for vm_core.h... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=C:/Ruby24/bin/$(RUBY_BASE_NAME)
        --with-ruby-dir
        --without-ruby-dir
        --with-ruby-include
        --without-ruby-include=${ruby-dir}/include
        --with-ruby-lib
        --without-ruby-lib=${ruby-dir}/lib
C:/Ruby24/lib/ruby/2.4.0/mkmf.rb:457:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
        from C:/Ruby24/lib/ruby/2.4.0/mkmf.rb:588:in `try_cpp'
        from C:/Ruby24/lib/ruby/2.4.0/mkmf.rb:1096:in `block in have_header'
        from C:/Ruby24/lib/ruby/2.4.0/mkmf.rb:946:in `block in checking_for'
        from C:/Ruby24/lib/ruby/2.4.0/mkmf.rb:351:in `block (2 levels) in postpone'
        from C:/Ruby24/lib/ruby/2.4.0/mkmf.rb:321:in `open'
        from C:/Ruby24/lib/ruby/2.4.0/mkmf.rb:351:in `block in postpone'
        from C:/Ruby24/lib/ruby/2.4.0/mkmf.rb:321:in `open'
        from C:/Ruby24/lib/ruby/2.4.0/mkmf.rb:347:in `postpone'
        from C:/Ruby24/lib/ruby/2.4.0/mkmf.rb:945:in `checking_for'
        from C:/Ruby24/lib/ruby/2.4.0/mkmf.rb:1095:in `have_header'
        from extconf.rb:8:in `block in <main>'
        from C:/Ruby24/lib/ruby/gems/2.4.0/gems/debase-ruby_core_source-0.10.4/lib/debase/ruby_core_source.rb:15:in `create_makefile_with_core'
        from extconf.rb:32:in `<main>'

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  C:/Ruby24/lib/ruby/gems/2.4.0/extensions/x86-mingw32/2.4.0/arg_scanner-0.3.0/mkmf.log

extconf failed, exit code 1`

mkmf.log:

`"i686-w64-mingw32-gcc -o conftest.exe -IC:/Ruby24/include/ruby-2.4.0/i386-mingw32 -IC:/Ruby24/include/ruby-2.4.0/ruby/backward -IC:/Ruby24/include/ruby-2.4.0 -I. -D_FORTIFY_SOURCE=2 -D__USE_MINGW_ANSI_STDIO=1 -DFD_SETSIZE=2048 -D_WIN32_WINNT=0x0501 -D__MINGW_USE_VC2005_COMPAT -D_FILE_OFFSET_BITS=64  -O3 -fno-fast-math `pkg-config --cflags --libs glib-2.0` conftest.c  -L. -LC:/Ruby24/lib -L. -pipe -s     -lmsvcrt-ruby240  -lgmp -lshell32 -lws2_32 -liphlpapi -limagehlp -lshlwapi  "
i686-w64-mingw32-gcc: error: `pkg-config: No such file or directory
i686-w64-mingw32-gcc: error: glib-2.0`: No such file or directory
i686-w64-mingw32-gcc: error: unrecognized command line option '--cflags'
i686-w64-mingw32-gcc: error: unrecognized command line option '--libs'
checked program was:
/* begin */
1: #include "ruby.h"
2:
3: #include <winsock2.h>
4: #include <windows.h>
5: int main(int argc, char **argv)
6: {
7:   return 0;
8: }
/* end */`
